---

services:
  nginx:
    build:
      context: ./requirements/nginx
    
    container_name: nginx
    
    ports:
      - "443:443"
    networks:
      - wp_network
    depends_on:
      - wordpress

  wordpress:
    build:
      context: ./requirements/wordpress
    
    container_name: wordpress
    
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    
    networks:
      - wp_network
#    depends_on:
#      - mariadb
    volumes:
      - wordpress_files:/var/www/wordpress

#   mariadb:
#     build:
#       context: ./requirements/mariadb
#   
#    container_name: mariadb
#
#    environment:
#       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#       MYSQL_DATABASE: ${MYSQL_DATABASE}
#       MYSQL_USER: ${MYSQL_USER}
#       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#   
#    networks:
#      - wp_network
#    volumes:
#      - wordpress_db:/var/lib/mysql
#
#
volumes:
  wordpress_files:
  wordpress_db: 

networks:
  wp_network:
    driver: bridge
