---

services:
  nginx:
    build:
      context: ./requirements/nginx

    container_name: nginx

    ports:
      - "443:443"
    networks:
      - wp_network
    depends_on:
      - wordpress

  wordpress:
    build:
      context: ./requirements/wordpress

    container_name: wordpress

    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_PORT: ${WORDPRESS_DB_PORT}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}

    networks:
      - wp_network
    depends_on:
      - mariadb
    volumes:
      - wordpress_files:/var/www/wordpress

  mariadb:
    build:
      context: ./requirements/mariadb
   
    ports:
      - "3306:3306"

    container_name: mariadb

    restart: always

    networks:
      - wp_network
    volumes:
      - wordpress_db:/var/lib/mysql
    
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}


volumes:
  wordpress_files:
  wordpress_db: 

networks:
  wp_network:
    driver: bridge
